### ISSUE TITLE
Recording as Money, but retrieving as CentAmount

### ISSUE THREAD

**Issue by circus-miguel** [labd/commercetools-go-sdk#79]
When I'm recording a new product, the expected type for price value is "platform.Money"
However, when I retrieve back this product using products()...Get()..., it returns the price as platform.CentPrecisionMoney.
**Is this the planned behaviour?**

### Here is how I'm saving/storing the product.price
```golang
	Prices: []platform.PriceDraft{
				{
					Value: platform.Money{
						CentAmount:   price,
						CurrencyCode: "EUR",
					},
					Country:       ctutils.StringRef(productPriceCountryDefault),
				},
			},

```

### Here is how I'm retrieving the product.price
```golang
	if len(dim.MasterVariant.Prices) > 0 {
		if priceValue, ok := dim.MasterVariant.Prices[0].Value.(platform.CentPrecisionMoney); ok {
			cp.Price = float64(priceValue.CentAmount) / 100.0
		}
	}

```

**Comment by demeyerthom** [comment]
Hi @circus-miguel! Thanks for reaching out, and apologies for the late reply!

It took me some time to figure this out, but here are my findings: According to some direct calls to the API we should be able to create both CentPrecision and HighPrecision money objects. the Money struct in this case should operate as the base money object, where the others extend from. 

By default the API will use CentPrecision, so that is why you are seeing the above results, but it should allow for HighPrecision too, which the SDK currently doesnt

This is however an issue with the [RAML API specs](https://github.com/commercetools/commercetools-api-reference/blob/c0441c90881cb274c54c0d999f05a490ec159d94/api-specs/api/types/common/PriceDraft.raml) from which we generate our SDK. There it only defines Money as input.

We have raised the issue with Commercetools to see if there is a fix possible here, but we will not diverge from the api reference, so for now consider it working as intended!
