### ISSUE TITLE
Add support for Advanced Product Search

### ISSUE THREAD

**Issue by ghandic** [labd/commercetools-go-sdk#90]
Seems like the only product search currently supported is ProductProjection searching, is it possible to search using [these doccos](https://docs.commercetools.com/merchant-center/advanced-product-search) if not, is it possible to add? Happy to raise a PR with some guidance!

**Comment by demeyerthom** [comment]
Hi @ghandic thanks for reaching out (and apologies for the late reply).

The advanced search is part of the pim-search api, which is not part of the official api specs as published her: https://github.com/commercetools/commercetools-api-reference/tree/main/api-specs

We try to keep this codebase purely to generated code based on the above api references, because maintenance would otherwise become a timesink.
